### ISSUE TITLE
Icon and banner color too similar

### ISSUE THREAD

**Issue by Philip-Scott** [bcedu/MuseIC#21]
The banner color you picked is too similar, (or the same) as the icon, and makes it hard to see. Try a lighter version of the color for the background :) 

![screenshot from 2017-09-17 11 53 27](https://user-images.githubusercontent.com/10786508/30523004-d5ea7e8e-9b9e-11e7-80ed-644549e1276f.png)

**Comment by bcedu** [comment]
Solved with https://github.com/bcedu/MuseIC/commit/4d189c394d907ea90048b30e567c2544e343b1ea
