### ISSUE TITLE
Hangs/Causes a "Force Quit or Wait" dialog while importing music directory.

### ISSUE THREAD

**Issue by DroWnThePoor** [bcedu/MuseIC#22]
As the title says, the app stops responding and the choose file/folder window stays open, while both generate the "force quit | wait " dialogue. My music directory is about 3200 songs.
On Loki, fully updated, using 3rd party icons/theming.

**Comment by bcedu** [comment]
It is probably  working on importing the files (reading them to get metadata about name, artist, album, etc.).
If you open the app through console you will see information about wich files is importing.

I will add a progress bar to show the progress of importation.

PD: wow 3200 songs! and I thought that my 2300 music library was enough big to test the app :)

Edit: I've found some files that are suposed to be ID3 but they are a mess: extra large "tags", strange chars, etc. I will try to detect them and avoid to make the whole proces of the file. By doing this, the importation will be faster.

**Comment by bcedu** [comment]
Closed with https://github.com/bcedu/MuseIC/commit/6dc05fff239f2041d047cf0252c8608f353e1f62, https://github.com/bcedu/MuseIC/commit/ab2c16ce1a97e8dab384913a008d72e127d50d4c  and 52768ddcd0f48559d00d3edde0547828a55d8475
