### ISSUE TITLE
Use default file dialog

### ISSUE THREAD

**Issue by jendamarek** [bcedu/MuseIC#26]
Have you considered using a default file dialog? I'd really like your app if it fitted more into the elementary os environment.

**Comment by bcedu** [comment]
@jendamarek do you talk about the file dialog shown when selectin files to open/add?

By the way, I’ve made a new release with huge improvements in the interface. It will be able soon in the app center. Hope you like it :)

**Comment by jendamarek** [comment]
Yes, I'm talking about that dialog. Looking forward to the new release.

**Comment by bcedu** [comment]
@jendamarek The problem with the default file dialog is that it don't allow select both files and folders, so I created my own file dialog. You can check out the question I made in stackoverflow: 

https://stackoverflow.com/questions/45153305/gtk-filechooserdialog-select-files-and-folders-vala

**Comment by bcedu** [comment]
@jendamarek By the way, I've checked the design changes you made in your fork. They are awesome. If you are interested, I would love you to make a Pull request with this changes to the main project.

**Comment by jendamarek** [comment]
Oh, I understand that, but you still have 2 buttons there, don't you?

As for the changes thanks, you can find the pull request here https://github.com/bcedu/MuseIC/pull/27
